### ISSUE TITLE
Test update server

### ISSUE THREAD

**Issue by brianteeman** [brianteeman/haraka#10]

**Comment by zero-24** [comment]
What do you mean with that issue? You can use dev, alpha, beta in the tags tag ;) in the backend you need to enable to get updates for that stabilities too. Let me know if you need help with that :)

**Comment by brianteeman** [comment]
It was more of a todo - i havent tested that updates actually work

**Comment by zero-24** [comment]
Ok you know how to contact me if you get any problems :) As i'm not arround for the next few days just ping me and i come back to you ;)

**Comment by brianteeman** [comment]
I am away until 30th as well

Leaving this open as a todo for me

**Comment by brianteeman** [comment]
Weird - it finds that there is an update but when you try to perform the update you get
> Invalid extension update

**Comment by brianteeman** [comment]
>Warning
Error connecting to the server: Illegal characters found in URL

>Error
Failed to download package. Download it and install manually from https://github.com/brianteeman/haraka/archive/1.0.3_beta.zip .

Because i have seen others do it I also tried wrapping the url in cdata - no difference

**Comment by brianteeman** [comment]
Woohoo it worked - had to make sure that their was no CS on the download section
