### ISSUE TITLE
Why use jQuery

### ISSUE THREAD

**Issue by C-Lodder** [brianteeman/haraka#13]
Is there not a vanilla version @dgt41

**Comment by brianteeman** [comment]
yes there were vanilla versions - i looked but they were nowhere near as well developed. This one has a lot of options - not really using them yet but might do

**Comment by dgt41** [comment]
@C-Lodder couple years ago I did an auctions component for a customer and I created the needed functions:
<img width="1275" alt="screen shot 2016-12-24 at 11 49 54" src="https://cloud.githubusercontent.com/assets/3889375/21466130/c4fba6ac-c9c6-11e6-96ff-a9e3c6bb8161.png">

@brianteeman to make this plugin universal (support any calendar) you need to get the date through the date.js of the media/fields/calendar/. I'll try to make a PR with those changes, if you're interested.
Oh also please don't use php files in the media folder, you can use the tmpl folder inside the plugin!

**Comment by brianteeman** [comment]
I am  not going to change the calendar.
I will take a look at using the tmpl folder. There was a reason I didn't
but I don't remember it now

**Comment by brianteeman** [comment]
See #14

**Comment by C-Lodder** [comment]
Yup, ignore that. Was just George being stupid
