### ISSUE TITLE
Client Access with IP address not working correctly

### ISSUE THREAD

**Issue by sandstorm871** [brianteeman/haraka#28]
Adding anything in the IP address field within the "Client Access" tab, allows the front-end website to be seen by anybody.

I tested with a Valid static IP & then changed my own IP via VPN, after clearing caches, changing browser & using incognito mode.

Tested with an invalid IP "123.456.789.10"
Also tested with just "123" with the same results.

Will try to take a deeper look, but thought it was best reported.
Really like the plugin & could see myself using it a lot. Have a couple of CSS/ styling improvement ideas too, which I'll have a play around with & share.

**Comment by brianteeman** [comment]
Thanks for reporting that - it does look like a bug indeed.

Will try to find some time to take a look at it over the next few days - unless someone else does it first

**Comment by zero-24** [comment]
Can be closed as we have a patch here #30

**Comment by brianteeman** [comment]
Closed

**Comment by brianteeman** [comment]
Thanks @zero-24 
@sandstorm871 I have released 1.0.13 now that will fix your problem
