### ISSUE TITLE
Notice: Undefined variable: fonts in plugins\system\haraka\tmpl\default.php on line 27

### ISSUE THREAD

**Issue by nordmograph** [brianteeman/haraka#38]
Hello,
$font is the array so I gess on line 27 $font[0] should be replacing $fonts
and
`<link href="//fonts.googleapis.com/css?family=<?php echo $font[1]; ?>" rel="stylesheet">` be added

**Comment by zero-24** [comment]
I have just done: https://github.com/brianteeman/haraka/pull/39

Please test as this should fix your issue 😄 Thanks.

**Comment by brianteeman** [comment]
If you can confirm this works for you then I will make a new release
